server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&serverTimezone=UTC
    username: root
    password: 1111
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml